# Generated by Django 5.2.17 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0002_competition_announcement")]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guided_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_teachers(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="proposal",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guided_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]


def _backfill_teachers(apps):
    Proposal = apps.get_model("core", "Proposal")
    Account = apps.get_model("core", "Account")
    for proposal in Proposal.objects.filter(teacher__isnull=True):
        guide = Account.objects.filter(school_id=proposal.school_id, role="teacher").order_by("id").first()
        if guide is None:
            raise RuntimeError(f"Proposal {proposal.pk} requires a teacher in its school before migration.")
        proposal.teacher_id = guide.pk
        proposal.save(update_fields=["teacher"])
