# Generated by Django 5.2.17 on 2026-08-12 12:07

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_proposal_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(default="research", max_length=30),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("draft", "待认领"), ("active", "进行中")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="invite_code",
            field=models.CharField(
                blank=True,
                default=apps.core.models.make_invite_code,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="school",
            name="license_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "平台管理员"),
                    ("teacher", "教师"),
                    ("student", "学生"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(default="探索新手", max_length=60)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_student", "等待学生确认"),
                            ("pending_teacher", "等待教师确认"),
                            ("approved", "已加入"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending_student",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "invitee")},
            },
        ),
    ]
