# Generated by Django 5.2.17 on 2026-08-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_project_type_project_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="report_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="material",
            name="report_section",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="material",
            name="required",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="core.school",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="core.school",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("unclaimed", "待认领"),
                    ("active", "进行中"),
                    ("completed", "已完成"),
                ],
                default="unclaimed",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MaterialAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="materials/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.materialrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_name", models.CharField(max_length=120)),
                ("stage_order", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("evidence_requirements", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "待解锁"),
                            ("available", "可开始"),
                            ("pending_review", "待审核"),
                            ("revision_required", "需修订"),
                            ("approved", "已通过"),
                            ("completed", "已完成"),
                        ],
                        default="locked",
                        max_length=24,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=100)),
                ("due_at", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.project",
                    ),
                ),
                (
                    "template_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.templatetask",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="core.projecttask",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttask",
            constraint=models.UniqueConstraint(
                fields=("project", "order"), name="unique_project_task_order"
            ),
        ),
    ]
