# Generated by Django 5.2.17 on 2026-08-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_normalize_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="problem",
            field=models.TextField(blank=True),
        ),
    ]
