# Generated by Django 5.2.17 on 2026-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_reportexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="publiccaserequest",
            name="application_scene",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="publiccaserequest",
            name="cover",
            field=models.ImageField(blank=True, upload_to="cases/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="publiccaserequest",
            name="discipline",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="publiccaserequest",
            name="outcome_form",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="publiccaserequest",
            name="selected_materials",
            field=models.ManyToManyField(
                blank=True, related_name="public_case_selections", to="core.material"
            ),
        ),
        migrations.AlterField(
            model_name="publiccaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_teacher", "教师审核"),
                    ("published", "已公开"),
                    ("offline", "已下架"),
                    ("rejected", "已拒绝"),
                ],
                default="pending_teacher",
                max_length=20,
            ),
        ),
    ]
