# Generated by Django 5.2.17 on 2026-08-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_publiccaserequest_application_scene_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="prompt",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "排队中"),
                    ("processing", "生成中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationlog",
            name="output",
            field=models.TextField(blank=True),
        ),
    ]
