# Generated by Django 5.2.17 on 2026-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_aigenerationlog_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialattachment",
            name="scan_detail",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="materialattachment",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待安全检查"),
                    ("processing", "检查中"),
                    ("clean", "安全"),
                    ("infected", "发现威胁"),
                    ("failed", "检查失败"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="materialattachment",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialattachment",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
