# Generated by Django 5.2.17 on 2026-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_attachment_security_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="publiccaserequest",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
    ]
