# Generated by Django 5.2.17 on 2026-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_publiccaserequest_review_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="status",
            field=models.CharField(default="draft", max_length=24),
        ),
        migrations.AlterField(
            model_name="materialrevision",
            name="status",
            field=models.CharField(default="draft", max_length=24),
        ),
    ]
