# Generated by Django 5.2.17 on 2026-08-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_material_status_alter_materialrevision_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Proposal",
        ),
    ]
