# Generated by Django 5.2.17 on 2026-08-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_uploadsession_uploadpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="attachment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upload_session",
                to="core.materialattachment",
            ),
        ),
    ]
