# Generated by Django 5.1 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_uploadsession_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgrowth",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
