# Generated by Django 5.2.17 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("revision_required", "需修订"),
                    ("approved", "已通过"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="materialrevision",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("revision_required", "需修订"),
                    ("approved", "已通过"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
    ]
