# Generated by Django 5.2.17 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_material_status_alter_materialrevision_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("school_updated", "学校配置已更新"),
                    ("invite_code_reset", "邀请码已重置"),
                    ("project_claimed", "项目已认领"),
                    ("member_invitation_decided", "成员邀请已处理"),
                    ("material_submitted", "材料已提交审核"),
                    ("material_reviewed", "材料审核已完成"),
                    ("case_submitted", "公开申请已提交"),
                    ("case_reviewed", "公开案例已审核"),
                    ("case_visibility_changed", "公开案例可见性已变更"),
                    ("report_export_requested", "报告导出已请求"),
                ],
                max_length=40,
            ),
        ),
    ]
