# Generated by Django 5.2.17 on 2026-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_material_guidance_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('available', '可开始'), ('pending_review', '待审核'), ('revision_required', '需修订'), ('approved', '已通过'), ('completed', '已完成')], default='available', max_length=24),
        ),
    ]
