# Generated by Django 5.2.17 on 2026-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_projecttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('school_updated', '学校配置已更新'), ('invite_code_reset', '邀请码已重置'), ('project_claimed', '项目已认领'), ('project_archived', '项目已归档'), ('project_trashed', '项目已移入回收站'), ('project_restored', '项目已恢复'), ('project_updated', '项目信息已更新'), ('member_invitation_decided', '成员邀请已处理'), ('member_assigned', '成员已分配'), ('material_submitted', '材料已提交审核'), ('material_reviewed', '材料审核已完成'), ('case_submitted', '公开申请已提交'), ('case_reviewed', '公开案例已审核'), ('case_visibility_changed', '公开案例可见性已变更'), ('report_export_requested', '报告导出已请求')], max_length=40),
        ),
    ]
