# Generated by Django 5.2.17 on 2026-08-18 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='agent_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('both', '师生通用')], default='student', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('system_instruction', models.TextField()),
                ('prompt_template', models.TextField()),
                ('input_schema', models.JSONField(blank=True, default=list)),
                ('context_scope_default', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to='core.school')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='core_agentt_role_aed285_idx'), models.Index(fields=['school', 'is_active'], name='core_agentt_school__76db11_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'school'), name='uniq_agent_key_school')],
            },
        ),
    ]
