# Generated by Django 5.2.17 on 2026-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_aigenerationlog_agent_key_agenttemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agenttemplate',
            name='uniq_agent_key_school',
        ),
        migrations.AddConstraint(
            model_name='agenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('school', None)), fields=('key',), name='uniq_global_agent_key'),
        ),
        migrations.AddConstraint(
            model_name='agenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('key', 'school'), name='uniq_school_agent_key'),
        ),
    ]
