# Generated by Django 5.2.17 on 2026-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_agenttemplate_uniq_agent_key_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationlog',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
