# Generated by Django 5.2.17 on 2026-08-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_aigenerationlog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='core.material'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='core.projecttask'),
        ),
    ]
