# Generated by Django 5.2.17 on 2026-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_ai_log_task_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='referenced_sources',
            field=models.JSONField(blank=True, default=list, help_text='本次生成实际读取的来源清单（步骤/材料/文件），供前端溯源展示'),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='extract_detail',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='extract_status',
            field=models.CharField(choices=[('pending', '待抽取'), ('processing', '抽取中'), ('done', '已抽取'), ('unsupported', '暂不支持的文件类型'), ('failed', '抽取失败')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='上传文件抽取的可读文本（PDF/Word/图片OCR），供 AI 上下文使用'),
        ),
    ]
