# Generated by Django 5.2.17 on 2026-08-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_aigenerationlog_referenced_sources_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttemplate",
            name="applicable_stages",
            field=models.JSONField(blank=True, default=list, help_text="适用研究阶段"),
        ),
        migrations.AddField(
            model_name="agenttemplate",
            name="output_contract",
            field=models.JSONField(
                blank=True, default=dict, help_text="结构化输出约定"
            ),
        ),
        migrations.AddField(
            model_name="agenttemplate",
            name="project_types",
            field=models.JSONField(blank=True, default=list, help_text="适用项目类型"),
        ),
        migrations.AddField(
            model_name="agenttemplate",
            name="quick_tasks",
            field=models.JSONField(
                blank=True, default=list, help_text="可触发该助手的快捷任务"
            ),
        ),
        migrations.AddField(
            model_name="agenttemplate",
            name="workflow",
            field=models.CharField(
                blank=True,
                default="",
                help_text="工作流标识，如 proposal 或 paper",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="artifact_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="结构化生成物；保留可写入材料的正文、标题及分段信息",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="paper_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="论文类型，如 empirical、review、case",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="saved_material_revision",
            field=models.OneToOneField(
                blank=True,
                help_text="由本次 AI 生成保存而成的不可变材料草稿",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_ai_log",
                to="core.materialrevision",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="verification_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="生成物中需要学生核验的文献、数据、事实清单",
            ),
        ),
    ]
