# Generated by Django 5.2.17 on 2026-08-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_aiconversation_aiconversationmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_logs",
                to="core.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_record",
                to="core.aiconversationmessage",
            ),
        ),
    ]
