# Generated by Django 5.2.17 on 2026-08-24 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_aigenerationlog_conversation_aigenerationlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='workspace_mode',
            field=models.CharField(choices=[('opening', '开题'), ('research', '研究'), ('defense', '答辩')], default='research', max_length=16),
        ),
        migrations.AddField(
            model_name='material',
            name='kind',
            field=models.CharField(choices=[('standard', '标准材料'), ('experiment_log', '实验日志')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='publiccaserequest',
            name='platform_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_public_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccaserequest',
            name='request_type',
            field=models.CharField(choices=[('student_school', '学生校内申请'), ('teacher_platform', '教师公域邀请')], default='student_school', max_length=20),
        ),
        migrations.AddField(
            model_name='publiccaserequest',
            name='student_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publiccaserequest',
            name='student_consent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consented_public_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiccaserequest',
            name='visibility_scope',
            field=models.CharField(choices=[('school', '校内'), ('platform', '全平台')], default='school', max_length=16),
        ),
        migrations.AddField(
            model_name='templatematerial',
            name='kind',
            field=models.CharField(choices=[('standard', '标准材料'), ('experiment_log', '实验日志')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='aigenerationlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='core.project'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('school_updated', '学校配置已更新'), ('invite_code_reset', '邀请码已重置'), ('project_claimed', '项目已认领'), ('project_archived', '项目已归档'), ('project_trashed', '项目已移入回收站'), ('project_restored', '项目已恢复'), ('project_updated', '项目信息已更新'), ('member_invitation_decided', '成员邀请已处理'), ('member_assigned', '成员已分配'), ('material_submitted', '材料已提交审核'), ('material_reviewed', '材料审核已完成'), ('case_submitted', '公开申请已提交'), ('case_reviewed', '公开案例已审核'), ('case_visibility_changed', '公开案例可见性已变更'), ('report_export_requested', '报告导出已请求'), ('ai_output_saved_as_material', 'AI 结果已保存为材料草稿'), ('ai_draft_confirmed_save', 'AI 草稿已确认保存'), ('student_consent_given', '学生已同意公域展示'), ('project_purged', '项目已清理')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invitation_accepted', '成员接受邀请'), ('invitation_rejected', '成员拒绝邀请'), ('member_assigned', '被加入项目'), ('material_approved', '材料已通过'), ('material_revision_required', '材料需修订'), ('case_published', '案例已发布'), ('case_rejected', '案例被驳回'), ('school_announcement', '学校通知'), ('platform_announcement', '平台公告'), ('invitation_pending', '邀请待处理'), ('review_feedback', '审核建议'), ('case_consent_required', '案例等待同意'), ('case_pending_platform', '案例待平台审核')], max_length=40),
        ),
        migrations.AlterField(
            model_name='publiccaserequest',
            name='status',
            field=models.CharField(choices=[('waiting_student', '等待学生同意'), ('pending_teacher', '教师审核'), ('pending_platform', '平台审核'), ('published', '已公开'), ('offline', '已下架'), ('rejected', '已拒绝')], default='pending_teacher', max_length=20),
        ),
    ]
