# Generated by Django 5.2.17 on 2026-08-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_functional_rearchitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='opening_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_conversations', to='core.project'),
        ),
    ]
