# Generated by Django 5.2.17 on 2026-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_aiconversation_opening_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='workspace_mode',
            field=models.CharField(choices=[('opening', '开题'), ('research', '研究'), ('defense', '答辩')], default='research', max_length=16),
        ),
    ]
