# Generated by Django 5.2.17 on 2026-08-31 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_backfill_ai_conversation_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=32, unique=True),
                ),
                ("encrypted_api_key", models.TextField()),
                ("masked_api_key", models.CharField(max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_platform_ai_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "平台 AI 配置",
                "verbose_name_plural": "平台 AI 配置",
            },
        ),
    ]
