# Generated by Django 5.2.17 on 2026-08-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_platform_ai_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformaiconfiguration",
            name="base_url",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="platformaiconfiguration",
            name="model",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
